# sources.py - Schlank ausgelagertes Quellverzeichnis (140+ Feeds)

SOURCES = [
    # 🇺🇸 1. USA: POLITISCHES SPEKTRUM & FINANZEN
    {"name": "CNN World", "url": "[http://rss.cnn.com/rss/edition.rss](http://rss.cnn.com/rss/edition.rss)", "cat": "US/Politik", "weight": 0.95, "bias": "US-LEFT-LIBERAL"},
    {"name": "MSNBC / NBC News", "url": "[https://feeds.nbcnews.com/nbcnews/public/news](https://feeds.nbcnews.com/nbcnews/public/news)", "cat": "US/Politik", "weight": 0.90, "bias": "US-LEFT-LIBERAL"},
    {"name": "New York Times World", "url": "[https://rss.nytimes.com/services/xml/rss/nyt/World.xml](https://rss.nytimes.com/services/xml/rss/nyt/World.xml)", "cat": "US/Presse", "weight": 0.95, "bias": "US-LEFT-LIBERAL"},
    {"name": "Fox News Latest", "url": "[https://moxie.foxnews.com/google-publisher/latest.xml](https://moxie.foxnews.com/google-publisher/latest.xml)", "cat": "US/Politik", "weight": 0.95, "bias": "US-CONSERVATIVE"},
    {"name": "National Review", "url": "[https://www.nationalreview.com/feed/](https://www.nationalreview.com/feed/)", "cat": "US/Politik", "weight": 0.85, "bias": "US-CONSERVATIVE"},
    {"name": "The Washington Times", "url": "[https://www.washingtontimes.com/rss/headlines/news/](https://www.washingtontimes.com/rss/headlines/news/)", "cat": "US/Politik", "weight": 0.85, "bias": "US-CONSERVATIVE"},
    {"name": "Wall Street Journal", "url": "[https://news.google.com/rss/search?q=when:24h+site:wsj.com](https://news.google.com/rss/search?q=when:24h+site:wsj.com)", "cat": "US/Finanzen", "weight": 0.95, "bias": "US-CONSERVATIVE-BUSINESS"},
    {"name": "Reason Magazine", "url": "[https://reason.com/feed/](https://reason.com/feed/)", "cat": "US/Debatte", "weight": 0.80, "bias": "US-LIBERTARIAN"},
    {"name": "Bloomberg Markets", "url": "[https://news.google.com/rss/search?q=when:24h+site:bloomberg.com](https://news.google.com/rss/search?q=when:24h+site:bloomberg.com)", "cat": "US/Finanzen", "weight": 0.95, "bias": "CENTER-LIBERAL"},

    # 🇩🇪 2. DEUTSCHLAND & DACH-RAUM
    {"name": "taz die tageszeitung", "url": "[https://taz.de/rss.xml](https://taz.de/rss.xml)", "cat": "DE/Politik", "weight": 0.85, "bias": "DE-LEFT-PROGRESSIVE"},
    {"name": "Der Spiegel", "url": "[https://www.spiegel.de/schlagzeilen/tops/index.rss](https://www.spiegel.de/schlagzeilen/tops/index.rss)", "cat": "DE/Medien", "weight": 0.90, "bias": "DE-LEFT-LIBERAL"},
    {"name": "Süddeutsche Zeitung", "url": "[https://news.google.com/rss/search?q=when:24h+site:sueddeutsche.de](https://news.google.com/rss/search?q=when:24h+site:sueddeutsche.de)", "cat": "DE/Presse", "weight": 0.90, "bias": "DE-LEFT-LIBERAL"},
    {"name": "FAZ Politik", "url": "[https://www.faz.net/rss/aktuell/politik/](https://www.faz.net/rss/aktuell/politik/)", "cat": "DE/Presse", "weight": 0.90, "bias": "DE-CONSERVATIVE"},
    {"name": "Die Welt", "url": "[https://www.welt.de/feeds/topnews.rss](https://www.welt.de/feeds/topnews.rss)", "cat": "DE/Presse", "weight": 0.85, "bias": "DE-CONSERVATIVE"},
    {"name": "NZZ International", "url": "[https://www.nzz.ch/international.rss](https://www.nzz.ch/international.rss)", "cat": "CH/Presse", "weight": 0.95, "bias": "DE-CONSERVATIVE-LIBERAL"},
    {"name": "Die Zeit Online", "url": "[https://newsfeed.zeit.de/index](https://newsfeed.zeit.de/index)", "cat": "DE/Presse", "weight": 0.90, "bias": "DE-CENTER-LIBERAL"},
    {"name": "Handelsblatt", "url": "[https://www.handelsblatt.com/contentexport/feed/top-themen](https://www.handelsblatt.com/contentexport/feed/top-themen)", "cat": "DE/Finanzen", "weight": 0.90, "bias": "DE-LIBERAL-BUSINESS"},

    # 🇬🇧 3. GROSSBRITANNIEN (UK)
    {"name": "The Guardian World", "url": "[https://www.theguardian.com/world/rss](https://www.theguardian.com/world/rss)", "cat": "UK/Presse", "weight": 0.90, "bias": "UK-LEFT-LIBERAL"},
    {"name": "The Telegraph", "url": "[https://news.google.com/rss/search?q=when:24h+site:telegraph.co.uk](https://news.google.com/rss/search?q=when:24h+site:telegraph.co.uk)", "cat": "UK/Presse", "weight": 0.85, "bias": "UK-CONSERVATIVE"},
    {"name": "The Spectator", "url": "[https://www.spectator.co.uk/feed/](https://www.spectator.co.uk/feed/)", "cat": "UK/Debatte", "weight": 0.80, "bias": "UK-CONSERVATIVE"},
    {"name": "BBC World News", "url": "[http://feeds.bbci.co.uk/news/world/rss.xml](http://feeds.bbci.co.uk/news/world/rss.xml)", "cat": "UK/Medien", "weight": 0.95, "bias": "MAINSTREAM-CENTER"},
    {"name": "Financial Times", "url": "[https://news.google.com/rss/search?q=when:24h+site:ft.com](https://news.google.com/rss/search?q=when:24h+site:ft.com)", "cat": "UK/Finanzen", "weight": 0.95, "bias": "CENTER-LIBERAL"},

    # 🏛️ 4. ZENTRALBANKEN, REGIERUNGEN & STAATLICHE STELLEN
    {"name": "Federal Reserve Press", "url": "[https://www.federalreserve.gov/feeds/press_all.xml](https://www.federalreserve.gov/feeds/press_all.xml)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "Fed Speeches & Minutes", "url": "[https://www.federalreserve.gov/feeds/speeches.xml](https://www.federalreserve.gov/feeds/speeches.xml)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "EZB (Europ. Zentralbank)", "url": "[https://www.ecb.europa.eu/rss/press.html](https://www.ecb.europa.eu/rss/press.html)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "Bank of England (BoE)", "url": "[https://www.bankofengland.co.uk/rss/news](https://www.bankofengland.co.uk/rss/news)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "People's Bank of China", "url": "[https://news.google.com/rss/search?q=when:7d+PBOC](https://news.google.com/rss/search?q=when:7d+PBOC)", "cat": "Zentralbank", "weight": 1.00, "bias": "BRICS"},
    {"name": "Bank of Japan (BoJ)", "url": "[https://news.google.com/rss/search?q=when:7d+Bank+of+Japan](https://news.google.com/rss/search?q=when:7d+Bank+of+Japan)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "Atlanta Fed / NY Fed", "url": "[https://news.google.com/rss/search?q=when:7d+GDPNow](https://news.google.com/rss/search?q=when:7d+GDPNow)", "cat": "Makro/Fed", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "BIS (Bank f. Intl. Zahl.)", "url": "[https://www.bis.org/doclist/all.rss](https://www.bis.org/doclist/all.rss)", "cat": "Zentralbank", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "IWF (IMF News)", "url": "[https://www.imf.org/en/News/rss](https://www.imf.org/en/News/rss)", "cat": "Intl. Org", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "Weltbank News", "url": "[https://www.worldbank.org/en/news/rss](https://www.worldbank.org/en/news/rss)", "cat": "Intl. Org", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "OECD Newsroom", "url": "[https://www.oecd.org/newsroom/index.xml](https://www.oecd.org/newsroom/index.xml)", "cat": "Intl. Org", "weight": 0.90, "bias": "OFFIZIELL"},
    {"name": "EU-Kommission Press", "url": "[https://ec.europa.eu/commission/presscorner/api/rss](https://ec.europa.eu/commission/presscorner/api/rss)", "cat": "Regierung/EU", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "Europäischer Rat", "url": "[https://www.consilium.europa.eu/en/rss/](https://www.consilium.europa.eu/en/rss/)", "cat": "Regierung/EU", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "White House Briefing", "url": "[https://www.whitehouse.gov/briefing-room/feed/](https://www.whitehouse.gov/briefing-room/feed/)", "cat": "Regierung", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "US Dept of State", "url": "[https://www.state.gov/rss-feed/press-releases/feed/](https://www.state.gov/rss-feed/press-releases/feed/)", "cat": "Diplomatie", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "Schweizer Bundesrat", "url": "[https://www.admin.ch/gov/de/start/dokumentation/medienmitteilungen.rss.html](https://www.admin.ch/gov/de/start/dokumentation/medienmitteilungen.rss.html)", "cat": "Regierung", "weight": 0.90, "bias": "OFFIZIELL"},

    # 🚶 5. MIGRATION, VERTREIBUNG & HUMANITÄRE DATEN
    {"name": "UNHCR Press Releases", "url": "[https://news.google.com/rss/search?q=when:7d+site:unhcr.org](https://news.google.com/rss/search?q=when:7d+site:unhcr.org)", "cat": "UNHCR", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "IOM DTM Tracking", "url": "[https://news.google.com/rss/search?q=when:7d+site:iom.int](https://news.google.com/rss/search?q=when:7d+site:iom.int)", "cat": "IOM", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "ReliefWeb UN OCHA", "url": "[https://reliefweb.int/updates/rss.xml](https://reliefweb.int/updates/rss.xml)", "cat": "Humanitär", "weight": 0.90, "bias": "OFFIZIELL"},
    {"name": "Frontex Alerts", "url": "[https://news.google.com/rss/search?q=when:7d+Frontex](https://news.google.com/rss/search?q=when:7d+Frontex)", "cat": "Grenzen", "weight": 0.90, "bias": "OFFIZIELL"},

    # 📊 6. ENERGIE, ROHSTOFFE, LOGISTIK & ANLEIHESTRESS
    {"name": "EIA Petroleum Report", "url": "[https://news.google.com/rss/search?q=when:7d+site:eia.gov](https://news.google.com/rss/search?q=when:7d+site:eia.gov)", "cat": "Energie", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "IEA Oil Reports", "url": "[https://news.google.com/rss/search?q=when:7d+site:iea.org](https://news.google.com/rss/search?q=when:7d+site:iea.org)", "cat": "Energie", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "OPEC Monthly Report", "url": "[https://news.google.com/rss/search?q=when:7d+OPEC](https://news.google.com/rss/search?q=when:7d+OPEC)", "cat": "Energie", "weight": 0.90, "bias": "OFFIZIELL"},
    {"name": "Baker Hughes Rig Count", "url": "[https://news.google.com/rss/search?q=when:7d+Baker+Hughes](https://news.google.com/rss/search?q=when:7d+Baker+Hughes)", "cat": "Energie", "weight": 0.85, "bias": "OFFIZIELL"},
    {"name": "AGSI+ Gas Storage", "url": "[https://news.google.com/rss/search?q=when:7d+Gas+Infrastructure+Europe](https://news.google.com/rss/search?q=when:7d+Gas+Infrastructure+Europe)", "cat": "Energie", "weight": 0.90, "bias": "OFFIZIELL"},
    {"name": "Freightos Shipping", "url": "[https://news.google.com/rss/search?q=when:7d+Freightos](https://news.google.com/rss/search?q=when:7d+Freightos)", "cat": "Container", "weight": 0.85, "bias": "LOGISTICS"},
    {"name": "Baltic Dry Index", "url": "[https://news.google.com/rss/search?q=when:7d+Baltic+Dry+Index](https://news.google.com/rss/search?q=when:7d+Baltic+Dry+Index)", "cat": "Logistik", "weight": 0.90, "bias": "LOGISTICS"},
    {"name": "FAO Food Price Index", "url": "[https://news.google.com/rss/search?q=when:7d+site:fao.org](https://news.google.com/rss/search?q=when:7d+site:fao.org)", "cat": "Agrar", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "USDA Crop WASDE", "url": "[https://news.google.com/rss/search?q=when:7d+site:usda.gov](https://news.google.com/rss/search?q=when:7d+site:usda.gov)", "cat": "Agrar", "weight": 0.90, "bias": "OFFIZIELL"},
    {"name": "MOVE Index / Bonds", "url": "[https://news.google.com/rss/search?q=when:7d+MOVE+index](https://news.google.com/rss/search?q=when:7d+MOVE+index)", "cat": "Bond Stress", "weight": 0.90, "bias": "MARKETS"},

    # 🛡️ 7. OSINT, MILITÄR, SATELLITEN, CYBER & SEE
    {"name": "Oryx Blog", "url": "[https://www.oryxspioenkop.com/feeds/posts/default](https://www.oryxspioenkop.com/feeds/posts/default)", "cat": "OSINT / Militär", "weight": 0.90, "bias": "ALTERNATIVE"},
    {"name": "Perun / Covert Cabal", "url": "[https://news.google.com/rss/search?q=when:7d+Perun+defense](https://news.google.com/rss/search?q=when:7d+Perun+defense)", "cat": "OSINT / Analyse", "weight": 0.85, "bias": "ANALYTICAL"},
    {"name": "Lloyd's List", "url": "[https://news.google.com/rss/search?q=when:7d+Lloyds+List](https://news.google.com/rss/search?q=when:7d+Lloyds+List)", "cat": "Schifffahrt", "weight": 0.90, "bias": "MARITIME"},
    {"name": "MarineTraffic Blog", "url": "[https://www.marinetraffic.com/blog/feed/](https://www.marinetraffic.com/blog/feed/)", "cat": "Marine OSINT", "weight": 0.85, "bias": "MARITIME"},
    {"name": "NASA FIRMS Hazards", "url": "[https://earthobservatory.nasa.gov/feeder/natural_hazards.rss](https://earthobservatory.nasa.gov/feeder/natural_hazards.rss)", "cat": "Satellit", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "USGS Earthquakes", "url": "[https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/5.5_day.atom](https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/5.5_day.atom)", "cat": "Seismik", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "GDACS Disaster Alerts", "url": "[https://www.gdacs.org/xml/rss.xml](https://www.gdacs.org/xml/rss.xml)", "cat": "Warnsystem", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "ISW (Study of War)", "url": "[https://www.understandingwar.org/rss.xml](https://www.understandingwar.org/rss.xml)", "cat": "Militäranalyse", "weight": 0.85, "bias": "WESTERN"},
    {"name": "US Naval Institute", "url": "[https://news.usni.org/feed](https://news.usni.org/feed)", "cat": "Marine OSINT", "weight": 0.90, "bias": "WESTERN-DEFENSE"},
    {"name": "Naval News", "url": "[https://www.navalnews.com/feed/](https://www.navalnews.com/feed/)", "cat": "Schifffahrt", "weight": 0.90, "bias": "WESTERN-DEFENSE"},
    {"name": "War on the Rocks", "url": "[https://warontherocks.com/feed/](https://warontherocks.com/feed/)", "cat": "Militäranalyse", "weight": 0.90, "bias": "WESTERN-DEFENSE"},
    {"name": "Bellingcat", "url": "[https://www.bellingcat.com/feed/](https://www.bellingcat.com/feed/)", "cat": "OSINT / Satellit", "weight": 0.90, "bias": "VERIFIED-OSINT"},
    {"name": "Critical Threats", "url": "[https://news.google.com/rss/search?q=when:7d+Critical+Threats](https://news.google.com/rss/search?q=when:7d+Critical+Threats)", "cat": "Militäranalyse", "weight": 0.85, "bias": "WESTERN"},
    {"name": "CISA Cyber Alerts", "url": "[https://www.cisa.gov/cybersecurity-advisories/all.xml](https://www.cisa.gov/cybersecurity-advisories/all.xml)", "cat": "Cyber / Infrastruktur", "weight": 1.00, "bias": "OFFIZIELL"},
    {"name": "CERT-EU", "url": "[https://cert.europa.eu/publications/warnings/feed.xml](https://cert.europa.eu/publications/warnings/feed.xml)", "cat": "Cyber / Infrastruktur", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "Dark Reading", "url": "[https://www.darkreading.com/rss.xml](https://www.darkreading.com/rss.xml)", "cat": "Cyber", "weight": 0.85, "bias": "CYBER-INDUSTRY"},
    {"name": "Submarine Telecoms", "url": "[https://subtelforum.com/feed/](https://subtelforum.com/feed/)", "cat": "Infrastruktur", "weight": 0.85, "bias": "INFRASTRUCTURE"},
    {"name": "Offshore Energy", "url": "[https://www.offshore-energy.biz/feed/](https://www.offshore-energy.biz/feed/)", "cat": "Infrastruktur", "weight": 0.85, "bias": "ENERGY-INDUSTRY"},
    {"name": "UKMTO Operations", "url": "[https://news.google.com/rss/search?q=when:24h+UKMTO](https://news.google.com/rss/search?q=when:24h+UKMTO)", "cat": "Schifffahrt", "weight": 0.95, "bias": "OFFIZIELL"},
    {"name": "gCaptain Maritime", "url": "[https://gcaptain.com/feed/](https://gcaptain.com/feed/)", "cat": "Schifffahrt", "weight": 0.85, "bias": "MARITIME"},
    {"name": "Splash247 Shipping", "url": "[https://splash247.com/feed/](https://splash247.com/feed/)", "cat": "Schifffahrt", "weight": 0.85, "bias": "MARITIME"},
    {"name": "Maritime Executive", "url": "[https://maritime-executive.com/rss](https://maritime-executive.com/rss)", "cat": "Schifffahrt", "weight": 0.85, "bias": "MARITIME"},
    {"name": "Flightradar24 Blog", "url": "[https://www.flightradar24.com/blog/feed/](https://www.flightradar24.com/blog/feed/)", "cat": "Luftfahrt OSINT", "weight": 0.85, "bias": "AVIATION"},
    {"name": "Aviation Safety Net", "url": "[https://news.google.com/rss/search?q=when:7d+Aviation+Safety+Network](https://news.google.com/rss/search?q=when:7d+Aviation+Safety+Network)", "cat": "Luftfahrt", "weight": 0.85, "bias": "AVIATION"},
    {"name": "GPSJam / EW Alerts", "url": "[https://news.google.com/rss/search?q=when:24h+GPS+jamming](https://news.google.com/rss/search?q=when:24h+GPS+jamming)", "cat": "EW / Luftfahrt", "weight": 0.85, "bias": "EW-OSINT"},

    # 🌍 8. WELT-NACHRICHTENAGENTUREN, DIPLOMATIE & BRICS
    {"name": "Associated Press (AP)", "url": "[https://news.google.com/rss/search?q=when:24h+source:Associated+Press](https://news.google.com/rss/search?q=when:24h+source:Associated+Press)", "cat": "Agentur", "weight": 0.95, "bias": "CENTER-NEUTRAL"},
    {"name": "Reuters World", "url": "[https://news.google.com/rss/search?q=when:24h+source:Reuters](https://news.google.com/rss/search?q=when:24h+source:Reuters)", "cat": "Agentur", "weight": 0.95, "bias": "CENTER-NEUTRAL"},
    {"name": "Agence France-Presse", "url": "[https://news.google.com/rss/search?q=when:24h+source:AFP](https://news.google.com/rss/search?q=when:24h+source:AFP)", "cat": "Agentur", "weight": 0.90, "bias": "EU-CENTER"},
    {"name": "Xinhua / Global Times", "url": "[https://news.google.com/rss/search?q=when:24h+site:xinhuanet.com](https://news.google.com/rss/search?q=when:24h+site:xinhuanet.com)", "cat": "BRICS", "weight": 0.85, "bias": "BRICS-CHINA"},
    {"name": "IRNA / Anadolu Agency", "url": "[https://news.google.com/rss/search?q=when:24h+site:irna.ir](https://news.google.com/rss/search?q=when:24h+site:irna.ir)", "cat": "BRICS", "weight": 0.80, "bias": "BRICS-MIDDLEEAST"},
    {"name": "Kyodo News", "url": "[https://english.kyodonews.net/rss/news.xml](https://english.kyodonews.net/rss/news.xml)", "cat": "Agentur", "weight": 0.85, "bias": "ASIA-WESTERN"},
    {"name": "Kremlin News", "url": "[http://en.kremlin.ru/rss/news](http://en.kremlin.ru/rss/news)", "cat": "BRICS / RU", "weight": 0.85, "bias": "BRICS-RUSSIA"},
    {"name": "Russ. Aussenministerium", "url": "[https://news.google.com/rss/search?q=when:7d+MID+Russia](https://news.google.com/rss/search?q=when:7d+MID+Russia)", "cat": "Diplomatie", "weight": 0.85, "bias": "BRICS-RUSSIA"},
    {"name": "Chin. Aussenministerium", "url": "[https://www.fmprc.gov.cn/eng/zxmz/rss.xml](https://www.fmprc.gov.cn/eng/zxmz/rss.xml)", "cat": "Diplomatie", "weight": 0.85, "bias": "BRICS-CHINA"},
    {"name": "Indisches Außenmin.", "url": "[https://news.google.com/rss/search?q=when:7d+site:mea.gov.in](https://news.google.com/rss/search?q=when:7d+site:mea.gov.in)", "cat": "BRICS / IN", "weight": 0.85, "bias": "BRICS-INDIA"},
    {"name": "CGTN World", "url": "[https://www.cgtn.com/xml/rss/news.xml](https://www.cgtn.com/xml/rss/news.xml)", "cat": "BRICS", "weight": 0.80, "bias": "BRICS-CHINA"},
    {"name": "TASS World", "url": "[https://tass.com/rss/v2.xml](https://tass.com/rss/v2.xml)", "cat": "BRICS", "weight": 0.80, "bias": "BRICS-RUSSIA"},
    {"name": "Economic Times India", "url": "[https://economictimes.indiatimes.com/rssfeeds/12216583.cms](https://economictimes.indiatimes.com/rssfeeds/12216583.cms)", "cat": "BRICS / IN", "weight": 0.85, "bias": "BRICS-INDIA"},
    {"name": "Al Jazeera", "url": "[https://www.aljazeera.com/xml/rss/all.xml](https://www.aljazeera.com/xml/rss/all.xml)", "cat": "BRICS / Arabisch", "weight": 0.85, "bias": "MIDDLEEAST-GLOBAL"},
    {"name": "South China Morning Post", "url": "[https://www.scmp.com/rss/91/feed](https://www.scmp.com/rss/91/feed)", "cat": "BRICS / HK", "weight": 0.85, "bias": "BRICS-ASIA"},
    {"name": "The Cradle", "url": "[https://thecradle.co/feed](https://thecradle.co/feed)", "cat": "Alternative", "weight": 0.80, "bias": "MIDDLEEAST-ALTERNATIVE"},
    {"name": "Asia Times", "url": "[https://asiatimes.com/feed/](https://asiatimes.com/feed/)", "cat": "Geopolitik", "weight": 0.85, "bias": "ASIA-ANALYTICAL"},

    # 💡 9. THINK TANKS & QUALITÄTSPRESSE
    {"name": "Quincy Institute", "url": "[https://quincyinst.org/feed/](https://quincyinst.org/feed/)", "cat": "Think Tank", "weight": 0.90, "bias": "REALIST-DIPLOMACY"},
    {"name": "Carnegie Endowment", "url": "[https://carnegieendowment.org/rss/solr.xml](https://carnegieendowment.org/rss/solr.xml)", "cat": "Think Tank", "weight": 0.90, "bias": "ANALYTICAL-CENTER"},
    {"name": "Chatham House", "url": "[https://www.chathamhouse.org/rss.xml](https://www.chathamhouse.org/rss.xml)", "cat": "Think Tank", "weight": 0.90, "bias": "UK-THINKTANK"},
    {"name": "Bruegel", "url": "[https://www.bruegel.org/rss.xml](https://www.bruegel.org/rss.xml)", "cat": "Think Tank/EU", "weight": 0.90, "bias": "EU-ECONOMICS"},
    {"name": "CSIS Org", "url": "[https://www.csis.org/nerve/rss](https://www.csis.org/nerve/rss)", "cat": "Think Tank", "weight": 0.90, "bias": "US-STRATEGIC"},
    {"name": "CFR", "url": "[https://www.cfr.org/rss/publication/feed](https://www.cfr.org/rss/publication/feed)", "cat": "Think Tank", "weight": 0.90, "bias": "US-ESTABLISHMENT"},
    {"name": "ECFR Europe", "url": "[https://ecfr.eu/feed/](https://ecfr.eu/feed/)", "cat": "Think Tank", "weight": 0.90, "bias": "EU-STRATEGIC"},
    {"name": "SWP Berlin", "url": "[https://www.swp-berlin.org/de/rss.xml](https://www.swp-berlin.org/de/rss.xml)", "cat": "Think Tank", "weight": 0.90, "bias": "DE-OFFICIAL-THINKTANK"},
    {"name": "World Economic Forum", "url": "[https://www.weforum.org/feed/](https://www.weforum.org/feed/)", "cat": "Think Tank", "weight": 0.85, "bias": "GLOBALIST-BUSINESS"},
    {"name": "CNBC Finance", "url": "[https://www.cnbc.com/id/10000664/device/rss/rss.html](https://www.cnbc.com/id/10000664/device/rss/rss.html)", "cat": "Finanzen", "weight": 0.85, "bias": "US-MARKETS"},
    {"name": "Foreign Policy", "url": "[https://foreignpolicy.com/feed/](https://foreignpolicy.com/feed/)", "cat": "Magazin", "weight": 0.90, "bias": "INTERNATIONAL-RELATIONS"},
    {"name": "Nikkei Asia", "url": "[https://asia.nikkei.com/rss/feed/nar](https://asia.nikkei.com/rss/feed/nar)", "cat": "Finanzen/Asien", "weight": 0.90, "bias": "ASIA-BUSINESS"},
    {"name": "Finanzmarktwelt", "url": "[https://finanzmarktwelt.de/feed/](https://finanzmarktwelt.de/feed/)", "cat": "Finanzen DE", "weight": 0.80, "bias": "DE-FINANCE-CRITICAL"},

    # 💬 10. REDDIT COMMUNITY OSINT FEEDS
    {"name": "r/geopolitics", "url": "[https://www.reddit.com/r/geopolitics/.rss](https://www.reddit.com/r/geopolitics/.rss)", "cat": "Community", "weight": 0.80, "bias": "COMMUNITY-ANALYTICAL"},
    {"name": "r/OSINT", "url": "[https://www.reddit.com/r/OSINT/.rss](https://www.reddit.com/r/OSINT/.rss)", "cat": "Community", "weight": 0.85, "bias": "COMMUNITY-TECHNICAL"},
    {"name": "r/CredibleDefense", "url": "[https://www.reddit.com/r/CredibleDefense/.rss](https://www.reddit.com/r/CredibleDefense/.rss)", "cat": "Community", "weight": 0.85, "bias": "COMMUNITY-DEFENSE"},
    {"name": "r/LessCredibleDefence", "url": "[https://www.reddit.com/r/LessCredibleDefence/.rss](https://www.reddit.com/r/LessCredibleDefence/.rss)", "cat": "Community", "weight": 0.70, "bias": "COMMUNITY-DEFENSE"},
    {"name": "r/Economics", "url": "[https://www.reddit.com/r/Economics/.rss](https://www.reddit.com/r/Economics/.rss)", "cat": "Community", "weight": 0.75, "bias": "COMMUNITY-MACRO"},
    {"name": "r/Macroeconomics", "url": "[https://www.reddit.com/r/Macroeconomics/.rss](https://www.reddit.com/r/Macroeconomics/.rss)", "cat": "Community", "weight": 0.75, "bias": "COMMUNITY-MACRO"},
    {"name": "r/Commodities", "url": "[https://www.reddit.com/r/Commodities/.rss](https://www.reddit.com/r/Commodities/.rss)", "cat": "Community", "weight": 0.75, "bias": "COMMUNITY-COMMODITIES"},

    # 🔍 11. INVESTIGATIV, ALTERNATIV & KONTRÄR
    {"name": "Scheerpost", "url": "[https://scheerpost.com/feed/](https://scheerpost.com/feed/)", "cat": "Investigativ", "weight": 0.80, "bias": "US-LEFT-CRITICAL"},
    {"name": "Naked Capitalism", "url": "[https://www.nakedcapitalism.com/feed](https://www.nakedcapitalism.com/feed)", "cat": "Makro", "weight": 0.85, "bias": "FINANCIAL-CRITIQUE"},
    {"name": "Consortium News", "url": "[https://consortiumnews.com/feed/](https://consortiumnews.com/feed/)", "cat": "Investigativ", "weight": 0.80, "bias": "COUNTER-NARRATIVE"},
    {"name": "Glenn Greenwald", "url": "[https://greenwald.substack.com/feed](https://greenwald.substack.com/feed)", "cat": "Journalismus", "weight": 0.85, "bias": "MEDIA-CRITIQUE"},
    {"name": "Aaron Maté Substack", "url": "[https://mate.substack.com/feed](https://mate.substack.com/feed)", "cat": "Journalismus", "weight": 0.80, "bias": "FOREIGN-POLICY-CRITIQUE"},
    {"name": "The Duran", "url": "[https://theduran.com/feed/](https://theduran.com/feed/)", "cat": "Geopolitik", "weight": 0.75, "bias": "BRICS-MULTIPOLAR"},
    {"name": "ZeroHedge", "url": "[http://feeds.feedburner.com/zerohedge/feed](http://feeds.feedburner.com/zerohedge/feed)", "cat": "Alternativ", "weight": 0.75, "bias": "CONTRARIAN-FINANCE"},
    {"name": "The Intercept", "url": "[https://theintercept.com/feed/](https://theintercept.com/feed/)", "cat": "Investigativ", "weight": 0.85, "bias": "INVESTIGATIVE-LEFT"},
    {"name": "The Grayzone", "url": "[https://thegrayzone.com/feed/](https://thegrayzone.com/feed/)", "cat": "Investigativ", "weight": 0.70, "bias": "ANTI-HEGEMONIC"},
    {"name": "Republik (Schweiz)", "url": "[https://www.republik.ch/feed](https://www.republik.ch/feed)", "cat": "Investigativ", "weight": 0.85, "bias": "INDEPENDENT-SWISS"},
    {"name": "MintPress News", "url": "[https://www.mintpressnews.com/feed/](https://www.mintpressnews.com/feed/)", "cat": "Alternativ", "weight": 0.70, "bias": "ANTI-IMPERIALIST"},
    {"name": "UnHerd", "url": "[https://unherd.com/feed/](https://unherd.com/feed/)", "cat": "Debatte", "weight": 0.85, "bias": "UK-CONTRARIAN"},
    {"name": "Antiwar.com", "url": "[https://www.antiwar.com/blog/feed/](https://www.antiwar.com/blog/feed/)", "cat": "Friedenspolitik", "weight": 0.80, "bias": "NON-INTERVENTIONIST"},
    {"name": "NachDenkSeiten", "url": "[https://www.nachdenkseiten.de/?feed=rss2](https://www.nachdenkseiten.de/?feed=rss2)", "cat": "Medienkritik", "weight": 0.80, "bias": "DE-ALTERNATIVE-LEFT"},
    {"name": "Apolut", "url": "[https://apolut.net/feed/](https://apolut.net/feed/)", "cat": "Alternativ DE", "weight": 0.70, "bias": "DE-ALTERNATIVE"},
    {"name": "Anti-Spiegel", "url": "[https://www.anti-spiegel.ru/feed/](https://www.anti-spiegel.ru/feed/)", "cat": "Alternativ RU/DE", "weight": 0.65, "bias": "PRO-RUSSIA-DE"},
    {"name": "Telepolis", "url": "[https://www.telepolis.de/news-atom.xml](https://www.telepolis.de/news-atom.xml)", "cat": "Magazin DE", "weight": 0.80, "bias": "DE-CRITICAL-TECH"},
    {"name": "Tichys Einblick", "url": "[https://www.tichyseinblick.de/feed/](https://www.tichyseinblick.de/feed/)", "cat": "Debatte DE", "weight": 0.75, "bias": "DE-CONSERVATIVE"},
    {"name": "Overton Magazin", "url": "[https://overton-magazin.de/feed/](https://overton-magazin.de/feed/)", "cat": "Geopolitik DE", "weight": 0.80, "bias": "DE-ANALYTICAL"},
    {"name": "Multipolar Magazin", "url": "[https://multipolar-magazin.de/feed](https://multipolar-magazin.de/feed)", "cat": "Geopolitik DE", "weight": 0.75, "bias": "DE-MULTIPOLAR"},
    {"name": "Manova / Rubikon", "url": "[https://www.manova.news/artikel.rss](https://www.manova.news/artikel.rss)", "cat": "Alternativ DE", "weight": 0.70, "bias": "DE-CRITICAL"},
    {"name": "Berliner Tageszeitung", "url": "[https://www.berlinertageszeitung.de/feed](https://www.berlinertageszeitung.de/feed)", "cat": "Medien DE", "weight": 0.70, "bias": "DE-INDEPENDENT"},
    {"name": "Hintergrund Magazin", "url": "[https://www.hintergrund.de/feed/](https://www.hintergrund.de/feed/)", "cat": "Geopolitik DE", "weight": 0.80, "bias": "DE-CRITICAL"},
    {"name": "Moon of Alabama", "url": "[https://www.moonofalabama.org/index.rdf](https://www.moonofalabama.org/index.rdf)", "cat": "Militär-Blog", "weight": 0.80, "bias": "TACTICAL-MILITARY-CRITIQUE"},
    {"name": "Caitlin Johnstone", "url": "[https://caitlinjohnstone.com.au/feed/](https://caitlinjohnstone.com.au/feed/)", "cat": "Kolumne", "weight": 0.75, "bias": "INDEPENDENT-OPINION"},

    # 🎯 12. ERGÄNZENDE PREDICTION MARKETS & REAL-TIME SIGNALS
    {"name": "Polymarket Geopolitics & War", "url": "[https://news.google.com/rss/search?q=when:24h+%22Polymarket%22+(geopolitics+OR+war+OR+election)&hl=en-US&gl=US&ceid=US:en](https://news.google.com/rss/search?q=when:24h+%22Polymarket%22+(geopolitics+OR+war+OR+election)&hl=en-US&gl=US&ceid=US:en)", "cat": "Prediction Markets", "weight": 0.95, "bias": "CROWD-WISDOM"},
    {"name": "Kalshi Macro Odds", "url": "[https://news.google.com/rss/search?q=when:24h+%22Kalshi%22+(odds+OR+fed)&hl=en-US&gl=US&ceid=US:en](https://news.google.com/rss/search?q=when:24h+%22Kalshi%22+(odds+OR+fed)&hl=en-US&gl=US&ceid=US:en)", "cat": "Prediction Markets", "weight": 0.90, "bias": "CROWD-WISDOM"},
    {"name": "X / Twitter OSINT Live", "url": "[https://news.google.com/rss/search?q=when:24h+(site:x.com+OR+site:twitter.com)+%22OSINT%22&hl=en-US&gl=US&ceid=US:en](https://news.google.com/rss/search?q=when:24h+(site:x.com+OR+site:twitter.com)+%22OSINT%22&hl=en-US&gl=US&ceid=US:en)", "cat": "OSINT / X", "weight": 0.85, "bias": "ALTERNATIVE"}
]
